<a href="https://colab.research.google.com/github/ayushm1998/machinelearning/blob/master/mathops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [4]:
a=np.array([2,7,1,99,4])
type(a)

NameError: ignored

In [0]:
import numpy as np

In [6]:
#creting 1d array
a=np.array([2,7,1,99,4])
type(a)


numpy.ndarray

In [7]:
a

array([ 2,  7,  1, 99,  4])

In [8]:
a[0]

2

In [9]:
b=np.array([12,17,11,99,14])
type(b)

numpy.ndarray

In [10]:
b[0]


12

In [11]:
a[1]+b[3]

106

In [12]:
a*2

array([  4,  14,   2, 198,   8])

In [13]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
a5=a+5

In [15]:
print(a5)

[  7  12   6 104   9]


In [16]:
a*b

array([  24,  119,   11, 9801,   56])

In [17]:
#double dimension array
x=np.array([ [2,5,8]  ,[3,6,1]                     ])
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x(0,0)

In [19]:
x(0)

TypeError: ignored

In [20]:
x[0]

array([2, 5, 8])

In [21]:
x[0,0]

2

In [22]:
x[1,2]

1

In [23]:
x[0][0]

2

In [24]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7


In [26]:
y

array([[ 9, 12, 15],
       [10, 13,  8]])

In [27]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [28]:
x


array([[2, 5, 8],
       [3, 6, 1]])

In [30]:
z=np.array([[2,7],[3,8],[2,9],[9,2] ])
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [31]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [32]:
x.shape

(2, 3)

In [33]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [34]:
z[0:]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [37]:
z[0:2,0:1]

array([[2],
       [3]])

In [38]:
x[0:,1]        

array([5, 6])

In [39]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [40]:
x[0:,0,2]

IndexError: ignored

In [41]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [42]:
z[1,[3]]

IndexError: ignored

In [43]:
z[0:3]

array([[2, 7],
       [3, 8],
       [2, 9]])

In [44]:
z[[0,2]]

array([[2, 7],
       [2, 9]])

In [0]:
z[1,4,[2]]

In [0]:
z[ 0,3 ]

In [0]:
z[0,2]

In [48]:
z[  [0,3],1]

array([7, 2])

In [49]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [50]:
z[  [0,3],[0,1]]

array([2, 2])

In [51]:
z[0:,[1]]

array([[7],
       [8],
       [9],
       [2]])

In [0]:
z[,1]

In [53]:
z[0:,1]

array([7, 8, 9, 2])

In [54]:
z[  0:,[0,1]]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [55]:
z[[1,2],1]

array([8, 9])

In [59]:
z[1:,1]

array([8, 9, 2])

In [0]:
z.reshape(3,2)

In [62]:
b

array([12, 17, 11, 99, 14])

In [63]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [64]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 2]])

In [0]:
q=  np.zeros((3,6))

In [67]:
q

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.zeros((3,4)datatype=int)

In [0]:
np.nonzero(2,3)